### ISSUE TITLE
What is the license of r7expander?

### ISSUE THREAD

**Issue by yhara** [nyuichi/r7expander#1]
Hello,

What is the license of r7expander? 

It looks very helpful to implement r7rs expander in [my implementation](https://github.com/biwascheme/biwascheme) and I'd like to know it is free license.

**Comment by nyuichi** [comment]
@yhara 
Thank you for reaching this project.
My preference is licensing under MIT, does that work for you?

**Comment by yhara** [comment]
> My preference is licensing under MIT, does that work for you?

@nyuichi Yes!
